[project]
name = "world-of-energy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter-book>=2.1.2",
    "jupytext>=1.19.1",
    "matplotlib>=3.10.8",
    "mystmd>=1.8.0",
    "numpy>=2.4.2",
]
